spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa # ?? db
    username: sa
    password:
    driver-class-name: org.h2.Driver # h2 db ??

  jpa:
    hibernate:
      ddl-auto: create # app ??? ? table drop ?? ?? ?? (drop-first ????)
    properties:
      hibernate:
        # show_sql: true  # jpa ????? console? ? ????
        format_sql: true  # ??? ??

logging.level:
  org.hibernate.SQL: debug # jpa ????? log? ????
# org.hibernate.type: trace # param?? ??
