spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa # db url
    username: sa
    password:
    driver-class-name: org.h2.Driver # using h2 db

  jpa:
    hibernate:
      ddl-auto: create # when app loading, table drop ( like drop-first: true )
    properties:
      hibernate:
        # show_sql: true  # write jpa query, at console
        format_sql: true  # formatting sql => prettier

logging.level:
  org.hibernate.SQL: debug # write jpa query, at log file
# org.hibernate.type: trace # write jpa query with param
